name: Prepare repo
description: "Checks out your repository and installs all your dependencies"
inputs:
  auth-token:
    description: "A token for interacting with the package registry. This will be set as the NODE_AUTH_TOKEN environment variable when initializing node."
    required: false
    default: ""
  registry-url:
    description: "The package registry to set up for authentication."
    required: false
    default: "https://registry.npmjs.org/"
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v2
      with:
        node-version-file: '.nvmrc'
        cache: yarn
        registry-url: ${{ inputs.registry-url }}
      env:
        NODE_AUTH_TOKEN: ${{ inputs.npm-token }}

    - name: Install dependencies
      run: yarn install --immutable
      shell: bash
