name: Prepare repo
description: "Checks out your repository and installs all your dependencies"
inputs:
  npm-token:
    description: "A token for interacting with NPM. This will be set as the NODE_AUTH_TOKEN environment variable when initializing node."
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v2
      with:
        node-version-file: '.nvmrc'
        cache: yarn
      env:
        NODE_AUTH_TOKEN: ${{ inputs.npm-token }}

    - name: Install dependencies
      run: yarn install --immutable
      shell: bash
